# Generated by Django 5.0.4 on 2024-08-23 12:41

import django.core.validators
import exam.exam_project.core.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), exam.exam_project.core.custom_validators.validate_all_letters], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), exam.exam_project.core.custom_validators.validate_all_letters], verbose_name='Last Name')),
                ('passcode', models.CharField(max_length=6, validators=[
                    exam.exam_project.core.custom_validators.validate_passcode])),
                ('pets_number', models.PositiveSmallIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Profile Image URL')),
            ],
        ),
    ]
